// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oejvwzhgwgdmbdsdahpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lanZ3emhnd2dkbWJkc2RhaHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjcyMzEsImV4cCI6MjA2NDkwMzIzMX0.enMKceuBIlZJ_EmftRuAG1AeBsGaBMrRTqInLZHrORI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);